Feature/#92
wafflestudio/draft-server pull request #94
Opened 2021-01-30 18:59 UTC by Hank-Choi

## 변경 사항
- 게임 로그 저장하는 api 생성
- 신규 service는 하나의 domain으로 묶을 수 있도록 service단 구성

2021-01-30 19:01 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/draft/api/RoomApiController.kt
> +        }
갑자기 작업하다 이쁘게 고침

2021-01-30 19:01 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/draft/api/RoomApiController.kt
> +        }
마찬가지로 이쁘게 고침

2021-01-30 19:06 UTC, Hank-Choi commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Server] 경기 기록 log 저장 API 개발](https://trello.com/c/O7tEb2ge/84-server-%EA%B2%BD%EA%B8%B0-%EA%B8%B0%EB%A1%9D-log-%EC%A0%80%EC%9E%A5-api-%EA%B0%9C%EB%B0%9C)

2021-01-31 06:10 UTC, sanggggg requested changes

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/repository/ParticipantRepository.kt
> +    fun getAllByRoom(room: Room?): List<Participant>?
`List<Participant>` 에서 ? 빼면 안됨? jpa 에서 없으면 안넣어 주는건 안되는가?

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/repository/RoomRepository.kt
> +    fun findRoomById(roomId:Long):Room?
[nitpick]
포매팅

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/api/RoomApiController.kt
> +        }
근데 apply 잘 써야하는게 외부에서 this 로 같은 필드 완전 안 들어갈 거 같은 상황에서만 사용합시다 (변수 쉐도잉 될 수 있음)
아니면 also!

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/dto/GameDTO.kt
> +            val gameScore: String? = null
구지 파싱해서 쓰지말고
teamLeftScore, teamRightScore 같이 따로 두개 받으면 안될까요?

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/dto/GameDTO.kt
> +            val gameScore: String? = null
마찬가지

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/model/Game.kt
> +    }
[nitpick]
포매팅, 포매팅 이상한 곳 꽤 많은듯 다 돌리면 좋을 거 같음

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/service/GameLogService.kt
> +        }
제안
```kotlin
val winningTeam: Team = request.gameScore?.split(":")!!.let { (teamAScore, teamBScore) ->
            when {
                teamAScore > teamBScore -> Team.A
                teamAScore < teamBScore -> Team.B
                else -> Team.NONE
            }
        }
```

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/service/GameLogService.kt
> +        }
근데 파싱 안하게 되면 결국 없어지겠군

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/service/GameLogService.kt
> +                winningTeam === Team.NONE -> GameResult.DRAW
제안
```kotlin
when(winningTeam) {
//...
}
```

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/service/GameLogService.kt
> +                winningTeam === Team.NONE -> GameResult.DRAW
그리고 === 쓸 필요 없어보이는데 (물론 enum 이라 ㄱㅊ겠지만)

2021-01-31 06:10 UTC, davin111 approved these changes
mostly LGTM

2021-01-31 06:10 UTC, davin111 commented on src/main/kotlin/com/wafflestudio/draft/dto/GameDTO.kt
> +}
사소한 파일 끝 newline

2021-01-31 06:10 UTC, davin111 commented on src/main/kotlin/com/wafflestudio/draft/model/UserGameLog.kt
> +): BaseTimeEntity()
요 방식이 더 나은 이유는 무엇인가여

2021-01-31 06:10 UTC, davin111 commented on src/main/kotlin/com/wafflestudio/draft/service/GameLogService.kt
> +}
사소한 파일 끝 newline

2021-01-31 06:10 UTC, davin111 commented on src/main/kotlin/com/wafflestudio/draft/service/GameLogService.kt
> +                teamAScore > teamBScore -> Team.A
저장되는 방식을 보니까, 클라 통해서 n:m 으로 score 받을 때, 이 순서가 굉장히 중요하겠다는 생각이 드네

2021-01-31 06:10 UTC, davin111 commented on src/main/kotlin/com/wafflestudio/draft/service/GameLogService.kt
> +                teamAScore > teamBScore -> Team.A
그런데 우리 현재 기획상, 하나의 방에서 어떤 Team이라는 model이 있고, 또 그 Team에 어떤 User(Player)들이 속하는지 등은 없는 상황인 거지? Team이 어떤 table로서 다뤄지지 않는 상황.

2021-01-31 06:10 UTC, davin111 commented on src/main/kotlin/com/wafflestudio/draft/dto/GameDTO.kt
> +    data class CreateRequest(
뭔가 게임이 중간에 터졌거나, 등등 다른 케이스에 대한 것도 하나 받아야할 수도 있겠다. 나중에 고민해도 될 수도 있겠지만.
예를 들면, result라는 것을 enum 정해놓고 따로 받아서, 1. 정상완료, 2. 비정상종료, 3. (이건 request로 받는 경우는 아니고) 끝났어야할 게임인데 클라로부터 관련 응답을 걍 못 받아서 2.처럼 취급되는 종료, 라든가.

2021-01-31 06:10 UTC, sanggggg commented on src/main/kotlin/com/wafflestudio/draft/dto/GameDTO.kt
> +            val gameScore: String? = null
or teamOneScore, teamTwoScore 하튼

2021-01-31 06:17 UTC, davin111 commented
그러고보니 [API 문서](https://draft-waffle.atlassian.net/wiki/spaces/DRAFTWAFFL/pages/33108/API+Documentation)에 요거 추가해주어야 할 듯합니다. 이거랑 같이 너가 지난 번에 제안한 https://stoplight.io/blog/rest-api-documentation-templates/ 병행해볼 수 있다고 생각하고? 이걸 첫 시작으로.

2021-01-31 06:38 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/draft/service/GameLogService.kt
> +        }
비교 제대로 안되지않음?

2021-02-06 11:54 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/draft/dto/GameDTO.kt
> +            val gameScore: String? = null
나도 어느정도 동의 @davin111 도 동의?

2021-02-06 11:56 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/draft/service/GameLogService.kt
> +                teamAScore > teamBScore -> Team.A
ㅇㅇ 그냥 플레이어의 필드에 team이 저장됨

2021-02-06 12:01 UTC, davin111 commented on src/main/kotlin/com/wafflestudio/draft/dto/GameDTO.kt
> +            val gameScore: String? = null
네

2021-02-06 12:12 UTC, Hank-Choi commented on src/main/kotlin/com/wafflestudio/draft/model/UserGameLog.kt
> +): BaseTimeEntity()
lombok처럼 getter setter 달아줘용

2021-02-07 03:54 UTC, sanggggg approved these changes

2021-02-07 04:01 UTC, merged